from .admin_panel import register_admin_menu_handlers
from .common_commands import register_common_handlers
from .data_search import register_data_search_handlers
from .main_menu_commands import register_main_menu_handlers
from .make_subscription import register_subscriptions_handlers
